name: main

on:
  push:
    branches:
      - master
      - '**'

env:
  GIT_SHA: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}
  CONTAINER_NAME: code-server-oauth2
  CHART_NAME: code-server-oauth2
  CHART_GIT_BRANCH: master
  CHART_REPOSITORY: szymonrychu/charts
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  BOT_EMAIL: "szymon.rychu@gmail.com"
  BOT_USERNAME: "szymonrychu"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: Parse versions in commit and setup debs
        run: |
          export LATEST_REPO_TAG=$(git tag -l --sort=-v:refname "[0-9]*" | head -n1)
          if [ -z "${LATEST_REPO_TAG}" ]; then
            export LATEST_REPO_TAG="0.0.1"
          fi
          export SHORT_SHA=$(echo ${GIT_SHA:0:7})

          export APP_VERSION=${LATEST_REPO_TAG}-${SHORT_SHA}
          export CHART_VERSION=${LATEST_REPO_TAG}-$(git show -s --format=%ct HEAD)-${SHORT_SHA}

          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "CHART_VERSION=${CHART_VERSION}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          echo "LATEST_REPO_TAG=${LATEST_REPO_TAG}" >> $GITHUB_ENV

          sudo wget https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Update metadata files
        run: |
          set -e
          cd chart
          yq w -i ${CHART_NAME}/Chart.yaml version ${CHART_VERSION}

      - name: Package and push helm chart
        run: |
          set -e

          cd chart

          CHART_PWD=$(pwd)

          helm dep update ${CHART_NAME}
          helm package -u ${CHART_NAME}

          git clone https://x-access-token:${BOT_TOKEN}@github.com/${CHART_REPOSITORY}.git /tmp/repo
          cd /tmp/repo
          git checkout ${CHART_GIT_BRANCH}

          mv ${CHART_PWD}/${CHART_NAME}-${CHART_VERSION}.tgz ./
          helm repo index .

          git config --global user.email "${BOT_EMAIL}"
          git config --global user.name "${BOT_USERNAME}"
          git add -A
          git commit -m "Add ${CHART_NAME} ${CHART_VERSION}"
          git push origin ${CHART_GIT_BRANCH}
